name: Execute shell script

on: push
#on: [push, fork]

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Read and list message
              run: ls -lart

            - name: Install cowsay program
              run: |
                chmod +x ./ascii.sh 
                ./ascii.sh